spring.application.name=visa-breno

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/visa_breno}
spring.datasource.username=${DB_USERNAME:breno}
spring.datasource.password=${DB_PASSWORD:visa_breno_dev}
